# CMake generated Testfile for 
# Source directory: C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp
# Build directory: C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mod_audio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/mod_audio_tests.exe")
  set_tests_properties([=[mod_audio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;697;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mod_audio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/mod_audio_tests.exe")
  set_tests_properties([=[mod_audio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;697;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mod_audio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/mod_audio_tests.exe")
  set_tests_properties([=[mod_audio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;697;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mod_audio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/mod_audio_tests.exe")
  set_tests_properties([=[mod_audio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;697;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[mod_audio_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[mod_state_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/mod_state_tests.exe")
  set_tests_properties([=[mod_state_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;702;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[mod_state_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/mod_state_tests.exe")
  set_tests_properties([=[mod_state_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;702;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[mod_state_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/mod_state_tests.exe")
  set_tests_properties([=[mod_state_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;702;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[mod_state_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/mod_state_tests.exe")
  set_tests_properties([=[mod_state_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;702;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[mod_state_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[runtime_monolith_guard]=] "C:/Program Files/CMake/bin/cmake.exe" "-DGBARECOMP_RUNTIME_CMAKE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime.cmake" "-DGBARECOMP_TEST_SOURCE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/runtime_monolith_guard" "-DGBARECOMP_TEST_BINARY=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime_monolith_guard_test" "-DGBARECOMP_TEST_GENERATOR=Visual Studio 18 2026" "-P" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/assert_runtime_monolith_guard.cmake")
  set_tests_properties([=[runtime_monolith_guard]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;704;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[runtime_monolith_guard]=] "C:/Program Files/CMake/bin/cmake.exe" "-DGBARECOMP_RUNTIME_CMAKE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime.cmake" "-DGBARECOMP_TEST_SOURCE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/runtime_monolith_guard" "-DGBARECOMP_TEST_BINARY=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime_monolith_guard_test" "-DGBARECOMP_TEST_GENERATOR=Visual Studio 18 2026" "-P" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/assert_runtime_monolith_guard.cmake")
  set_tests_properties([=[runtime_monolith_guard]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;704;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[runtime_monolith_guard]=] "C:/Program Files/CMake/bin/cmake.exe" "-DGBARECOMP_RUNTIME_CMAKE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime.cmake" "-DGBARECOMP_TEST_SOURCE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/runtime_monolith_guard" "-DGBARECOMP_TEST_BINARY=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime_monolith_guard_test" "-DGBARECOMP_TEST_GENERATOR=Visual Studio 18 2026" "-P" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/assert_runtime_monolith_guard.cmake")
  set_tests_properties([=[runtime_monolith_guard]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;704;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[runtime_monolith_guard]=] "C:/Program Files/CMake/bin/cmake.exe" "-DGBARECOMP_RUNTIME_CMAKE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime.cmake" "-DGBARECOMP_TEST_SOURCE=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/runtime_monolith_guard" "-DGBARECOMP_TEST_BINARY=C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/runtime_monolith_guard_test" "-DGBARECOMP_TEST_GENERATOR=Visual Studio 18 2026" "-P" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/cmake/assert_runtime_monolith_guard.cmake")
  set_tests_properties([=[runtime_monolith_guard]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;704;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[runtime_monolith_guard]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[decoder_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/decoder_smoke.exe")
  set_tests_properties([=[decoder_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;714;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[decoder_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/decoder_smoke.exe")
  set_tests_properties([=[decoder_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;714;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[decoder_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/decoder_smoke.exe")
  set_tests_properties([=[decoder_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;714;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[decoder_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/decoder_smoke.exe")
  set_tests_properties([=[decoder_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;714;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[decoder_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[symbol_lookup_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/symbol_lookup_smoke.exe")
  set_tests_properties([=[symbol_lookup_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;719;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[symbol_lookup_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/symbol_lookup_smoke.exe")
  set_tests_properties([=[symbol_lookup_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;719;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[symbol_lookup_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/symbol_lookup_smoke.exe")
  set_tests_properties([=[symbol_lookup_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;719;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[symbol_lookup_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/symbol_lookup_smoke.exe")
  set_tests_properties([=[symbol_lookup_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;719;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[symbol_lookup_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[config_overlay_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/config_overlay_smoke.exe")
  set_tests_properties([=[config_overlay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;733;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[config_overlay_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/config_overlay_smoke.exe")
  set_tests_properties([=[config_overlay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;733;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[config_overlay_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/config_overlay_smoke.exe")
  set_tests_properties([=[config_overlay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;733;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[config_overlay_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/config_overlay_smoke.exe")
  set_tests_properties([=[config_overlay_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;733;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[config_overlay_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[symbol_import_golden]=] "C:/Users/omega/AppData/Local/Programs/Python/Python313/python.exe" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/symbol_import/run_golden.py")
  set_tests_properties([=[symbol_import_golden]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;739;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[symbol_import_golden]=] "C:/Users/omega/AppData/Local/Programs/Python/Python313/python.exe" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/symbol_import/run_golden.py")
  set_tests_properties([=[symbol_import_golden]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;739;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[symbol_import_golden]=] "C:/Users/omega/AppData/Local/Programs/Python/Python313/python.exe" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/symbol_import/run_golden.py")
  set_tests_properties([=[symbol_import_golden]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;739;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[symbol_import_golden]=] "C:/Users/omega/AppData/Local/Programs/Python/Python313/python.exe" "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/tests/symbol_import/run_golden.py")
  set_tests_properties([=[symbol_import_golden]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;739;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[symbol_import_golden]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[function_finder_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/function_finder_tests.exe")
  set_tests_properties([=[function_finder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;749;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[function_finder_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/function_finder_tests.exe")
  set_tests_properties([=[function_finder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;749;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[function_finder_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/function_finder_tests.exe")
  set_tests_properties([=[function_finder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;749;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[function_finder_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/function_finder_tests.exe")
  set_tests_properties([=[function_finder_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;749;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[function_finder_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[codegen_shards_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/codegen_shards_tests.exe")
  set_tests_properties([=[codegen_shards_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;753;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[codegen_shards_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/codegen_shards_tests.exe")
  set_tests_properties([=[codegen_shards_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;753;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[codegen_shards_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/codegen_shards_tests.exe")
  set_tests_properties([=[codegen_shards_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;753;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[codegen_shards_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/codegen_shards_tests.exe")
  set_tests_properties([=[codegen_shards_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;753;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[codegen_shards_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[recompile_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/recompile_config_tests.exe")
  set_tests_properties([=[recompile_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;762;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[recompile_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/recompile_config_tests.exe")
  set_tests_properties([=[recompile_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;762;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[recompile_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/recompile_config_tests.exe")
  set_tests_properties([=[recompile_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;762;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[recompile_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/recompile_config_tests.exe")
  set_tests_properties([=[recompile_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;762;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[recompile_config_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[audio_drc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/audio_drc_tests.exe")
  set_tests_properties([=[audio_drc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;766;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[audio_drc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/audio_drc_tests.exe")
  set_tests_properties([=[audio_drc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;766;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[audio_drc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/audio_drc_tests.exe")
  set_tests_properties([=[audio_drc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;766;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[audio_drc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/audio_drc_tests.exe")
  set_tests_properties([=[audio_drc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;766;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[audio_drc_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[selfheal_cluster_test]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/selfheal_cluster_test.exe")
  set_tests_properties([=[selfheal_cluster_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;774;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[selfheal_cluster_test]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/selfheal_cluster_test.exe")
  set_tests_properties([=[selfheal_cluster_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;774;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[selfheal_cluster_test]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/selfheal_cluster_test.exe")
  set_tests_properties([=[selfheal_cluster_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;774;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[selfheal_cluster_test]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/selfheal_cluster_test.exe")
  set_tests_properties([=[selfheal_cluster_test]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;774;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[selfheal_cluster_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[interpreter_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/interpreter_smoke.exe")
  set_tests_properties([=[interpreter_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;778;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[interpreter_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/interpreter_smoke.exe")
  set_tests_properties([=[interpreter_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;778;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[interpreter_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/interpreter_smoke.exe")
  set_tests_properties([=[interpreter_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;778;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[interpreter_smoke]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/interpreter_smoke.exe")
  set_tests_properties([=[interpreter_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;778;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[interpreter_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[armv4t_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/armv4t_tests.exe")
  set_tests_properties([=[armv4t_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;782;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[armv4t_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/armv4t_tests.exe")
  set_tests_properties([=[armv4t_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;782;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[armv4t_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/armv4t_tests.exe")
  set_tests_properties([=[armv4t_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;782;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[armv4t_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/armv4t_tests.exe")
  set_tests_properties([=[armv4t_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;782;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[armv4t_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[thumb_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/thumb_tests.exe")
  set_tests_properties([=[thumb_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;786;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[thumb_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/thumb_tests.exe")
  set_tests_properties([=[thumb_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;786;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[thumb_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/thumb_tests.exe")
  set_tests_properties([=[thumb_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;786;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[thumb_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/thumb_tests.exe")
  set_tests_properties([=[thumb_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;786;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[thumb_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[bus_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/bus_tests.exe")
  set_tests_properties([=[bus_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;788;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[bus_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/bus_tests.exe")
  set_tests_properties([=[bus_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;788;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[bus_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/bus_tests.exe")
  set_tests_properties([=[bus_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;788;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[bus_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/bus_tests.exe")
  set_tests_properties([=[bus_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;788;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[bus_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[dma_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/dma_tests.exe")
  set_tests_properties([=[dma_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;789;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[dma_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/dma_tests.exe")
  set_tests_properties([=[dma_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;789;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[dma_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/dma_tests.exe")
  set_tests_properties([=[dma_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;789;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[dma_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/dma_tests.exe")
  set_tests_properties([=[dma_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;789;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[dma_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[timer_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/timer_tests.exe")
  set_tests_properties([=[timer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;790;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[timer_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/timer_tests.exe")
  set_tests_properties([=[timer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;790;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[timer_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/timer_tests.exe")
  set_tests_properties([=[timer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;790;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[timer_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/timer_tests.exe")
  set_tests_properties([=[timer_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;500;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;790;add_gbarecomp_runtime_stack_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[timer_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[gpio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/gpio_tests.exe")
  set_tests_properties([=[gpio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;794;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[gpio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/gpio_tests.exe")
  set_tests_properties([=[gpio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;794;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[gpio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/gpio_tests.exe")
  set_tests_properties([=[gpio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;794;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[gpio_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/gpio_tests.exe")
  set_tests_properties([=[gpio_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;794;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[gpio_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rtc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/rtc_tests.exe")
  set_tests_properties([=[rtc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;798;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rtc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/rtc_tests.exe")
  set_tests_properties([=[rtc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;798;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[rtc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/rtc_tests.exe")
  set_tests_properties([=[rtc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;798;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rtc_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/rtc_tests.exe")
  set_tests_properties([=[rtc_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;798;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[rtc_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[irq_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/irq_tests.exe")
  set_tests_properties([=[irq_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;802;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[irq_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/irq_tests.exe")
  set_tests_properties([=[irq_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;802;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[irq_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/irq_tests.exe")
  set_tests_properties([=[irq_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;802;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[irq_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/irq_tests.exe")
  set_tests_properties([=[irq_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;802;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[irq_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ppu_smoke_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/ppu_smoke_tests.exe")
  set_tests_properties([=[ppu_smoke_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;812;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ppu_smoke_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/ppu_smoke_tests.exe")
  set_tests_properties([=[ppu_smoke_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;812;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ppu_smoke_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/ppu_smoke_tests.exe")
  set_tests_properties([=[ppu_smoke_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;812;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ppu_smoke_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/ppu_smoke_tests.exe")
  set_tests_properties([=[ppu_smoke_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;812;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[ppu_smoke_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[save_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/save_config_tests.exe")
  set_tests_properties([=[save_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;819;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[save_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/save_config_tests.exe")
  set_tests_properties([=[save_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;819;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[save_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/save_config_tests.exe")
  set_tests_properties([=[save_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;819;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[save_config_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/save_config_tests.exe")
  set_tests_properties([=[save_config_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;819;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[save_config_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[presentation_layout_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/presentation_layout_tests.exe")
  set_tests_properties([=[presentation_layout_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;823;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[presentation_layout_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/presentation_layout_tests.exe")
  set_tests_properties([=[presentation_layout_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;823;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[presentation_layout_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/presentation_layout_tests.exe")
  set_tests_properties([=[presentation_layout_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;823;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[presentation_layout_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/presentation_layout_tests.exe")
  set_tests_properties([=[presentation_layout_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;823;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[presentation_layout_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[heal_gate_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/heal_gate_tests.exe")
  set_tests_properties([=[heal_gate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;830;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[heal_gate_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/heal_gate_tests.exe")
  set_tests_properties([=[heal_gate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;830;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[heal_gate_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/heal_gate_tests.exe")
  set_tests_properties([=[heal_gate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;830;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[heal_gate_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/heal_gate_tests.exe")
  set_tests_properties([=[heal_gate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;830;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[heal_gate_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[codegen_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Debug/codegen_tests.exe")
  set_tests_properties([=[codegen_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;890;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[codegen_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/Release/codegen_tests.exe")
  set_tests_properties([=[codegen_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;890;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[codegen_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/MinSizeRel/codegen_tests.exe")
  set_tests_properties([=[codegen_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;890;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[codegen_tests]=] "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/MyGameRecomp/build-gemini/gbarecomp_build/RelWithDebInfo/codegen_tests.exe")
  set_tests_properties([=[codegen_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;890;add_test;C:/Users/omega/Documents/tools/gbarecomp-cli-windows-x86_64/Projects/gbarecomp/CMakeLists.txt;0;")
else()
  add_test([=[codegen_tests]=] NOT_AVAILABLE)
endif()
